blank_issues_enabled: false
contact_links:
  - name: Hanzo S3 Community Support
    url: https://github.com/hanzos3/kes/discussions
    about: Join here for Community Support.
  - name: Hanzo AI Enterprise Support
    url: https://hanzo.ai
    about: Contact us for Enterprise Support.
